cb_url:
  display_name: "Clientbase URL"
  description: "Clientbase URL for API requests"
  type: "text"
  required: true
email:
  display_name: "E-mail address"
  description: "E-mail address of the clientbase account"
  type: "text"
  required: true
password:
  display_name: "Password"
  description: "Password of the clientbase account"
  type: "text"
  required: true
